//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.api.ws.rsi.com/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.api.ws.rsi.com/")]
    public partial class period
    {
        
        private string dateTimeFromField;
        
        private string dateTimeToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dateTimeFrom
        {
            get
            {
                return this.dateTimeFromField;
            }
            set
            {
                this.dateTimeFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dateTimeTo
        {
            get
            {
                return this.dateTimeToField;
            }
            set
            {
                this.dateTimeToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.api.ws.rsi.com/")]
    public partial class updateReservationDTO
    {
        
        private int idField;
        
        private period periodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public period period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.api.ws.rsi.com/", ConfigurationName="RentService.ICarRentalService")]
    public interface ICarRentalService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces.api.ws.rsi.com/ICarRentalService/updateReservationRequest", ReplyAction="http://interfaces.api.ws.rsi.com/ICarRentalService/updateReservationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RentService.Exception), Action="http://interfaces.api.ws.rsi.com/ICarRentalService/updateReservation/Fault/Except" +
            "ion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RentService.updateReservationResponse> updateReservationAsync(RentService.updateReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces.api.ws.rsi.com/ICarRentalService/getAllReservationsRequest", ReplyAction="http://interfaces.api.ws.rsi.com/ICarRentalService/getAllReservationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RentService.getAllReservationsResponse> getAllReservationsAsync(RentService.getAllReservationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateReservation", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class updateReservationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.api.ws.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RentService.updateReservationDTO reservation;
        
        public updateReservationRequest()
        {
        }
        
        public updateReservationRequest(RentService.updateReservationDTO reservation)
        {
            this.reservation = reservation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateReservationResponse", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class updateReservationResponse
    {
        
        public updateReservationResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.api.ws.rsi.com/")]
    public partial class reservation
    {
        
        private int carIdField;
        
        private int idField;
        
        private period periodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int carId
        {
            get
            {
                return this.carIdField;
            }
            set
            {
                this.carIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public period period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllReservations", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class getAllReservationsRequest
    {
        
        public getAllReservationsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllReservationsResponse", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class getAllReservationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.api.ws.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RentService.reservation[] @return;
        
        public getAllReservationsResponse()
        {
        }
        
        public getAllReservationsResponse(RentService.reservation[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ICarRentalServiceChannel : RentService.ICarRentalService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CarRentalServiceClient : System.ServiceModel.ClientBase<RentService.ICarRentalService>, RentService.ICarRentalService
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CarRentalServiceClient() : 
                base(CarRentalServiceClient.GetDefaultBinding(), CarRentalServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CarRentalServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRentalServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CarRentalServiceClient.GetBindingForEndpoint(endpointConfiguration), CarRentalServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRentalServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CarRentalServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRentalServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CarRentalServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRentalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentService.updateReservationResponse> RentService.ICarRentalService.updateReservationAsync(RentService.updateReservationRequest request)
        {
            return base.Channel.updateReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentService.updateReservationResponse> updateReservationAsync(RentService.updateReservationDTO reservation)
        {
            RentService.updateReservationRequest inValue = new RentService.updateReservationRequest();
            inValue.reservation = reservation;
            return ((RentService.ICarRentalService)(this)).updateReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentService.getAllReservationsResponse> RentService.ICarRentalService.getAllReservationsAsync(RentService.getAllReservationsRequest request)
        {
            return base.Channel.getAllReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentService.getAllReservationsResponse> getAllReservationsAsync()
        {
            RentService.getAllReservationsRequest inValue = new RentService.getAllReservationsRequest();
            return ((RentService.ICarRentalService)(this)).getAllReservationsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarRentalServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarRentalServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/CarRentalService");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CarRentalServiceClient.GetBindingForEndpoint(EndpointConfiguration.CarRentalServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CarRentalServiceClient.GetEndpointAddress(EndpointConfiguration.CarRentalServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            CarRentalServicePort,
        }
    }
}
