//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.api.ws.rsi.com/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.api.ws.rsi.com/")]
    public partial class addReservationDTO
    {
        
        private int carIdField;
        
        private period periodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int carId
        {
            get
            {
                return this.carIdField;
            }
            set
            {
                this.carIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public period period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.api.ws.rsi.com/")]
    public partial class period
    {
        
        private string dateTimeFromField;
        
        private string dateTimeToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dateTimeFrom
        {
            get
            {
                return this.dateTimeFromField;
            }
            set
            {
                this.dateTimeFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dateTimeTo
        {
            get
            {
                return this.dateTimeToField;
            }
            set
            {
                this.dateTimeToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces.api.ws.rsi.com/")]
    public partial class getCarDTO
    {
        
        private string descriptionField;
        
        private int idField;
        
        private string imgSrcField;
        
        private string modelField;
        
        private int numberOfSeatsField;
        
        private period[] unavailablePeriodsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string imgSrc
        {
            get
            {
                return this.imgSrcField;
            }
            set
            {
                this.imgSrcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numberOfSeats
        {
            get
            {
                return this.numberOfSeatsField;
            }
            set
            {
                this.numberOfSeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unavailablePeriods", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public period[] unavailablePeriods
        {
            get
            {
                return this.unavailablePeriodsField;
            }
            set
            {
                this.unavailablePeriodsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.api.ws.rsi.com/", ConfigurationName="CarService.ICarCatalogService")]
    public interface ICarCatalogService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces.api.ws.rsi.com/ICarCatalogService/getAllCarsRequest", ReplyAction="http://interfaces.api.ws.rsi.com/ICarCatalogService/getAllCarsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CarService.getAllCarsResponse> getAllCarsAsync(CarService.getAllCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces.api.ws.rsi.com/ICarCatalogService/reserveRequest", ReplyAction="http://interfaces.api.ws.rsi.com/ICarCatalogService/reserveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CarService.Exception), Action="http://interfaces.api.ws.rsi.com/ICarCatalogService/reserve/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CarService.reserveResponse> reserveAsync(CarService.reserveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces.api.ws.rsi.com/ICarCatalogService/getCarRequest", ReplyAction="http://interfaces.api.ws.rsi.com/ICarCatalogService/getCarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CarService.getCarResponse> getCarAsync(CarService.getCarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCars", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class getAllCarsRequest
    {
        
        public getAllCarsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCarsResponse", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class getAllCarsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.api.ws.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarService.getCarDTO[] @return;
        
        public getAllCarsResponse()
        {
        }
        
        public getAllCarsResponse(CarService.getCarDTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reserve", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class reserveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.api.ws.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarService.addReservationDTO reservation;
        
        public reserveRequest()
        {
        }
        
        public reserveRequest(CarService.addReservationDTO reservation)
        {
            this.reservation = reservation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reserveResponse", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class reserveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.api.ws.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public reserveResponse()
        {
        }
        
        public reserveResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCar", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class getCarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.api.ws.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getCarRequest()
        {
        }
        
        public getCarRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCarResponse", WrapperNamespace="http://interfaces.api.ws.rsi.com/", IsWrapped=true)]
    public partial class getCarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interfaces.api.ws.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarService.getCarDTO @return;
        
        public getCarResponse()
        {
        }
        
        public getCarResponse(CarService.getCarDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ICarCatalogServiceChannel : CarService.ICarCatalogService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CarCatalogServiceClient : System.ServiceModel.ClientBase<CarService.ICarCatalogService>, CarService.ICarCatalogService
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CarCatalogServiceClient() : 
                base(CarCatalogServiceClient.GetDefaultBinding(), CarCatalogServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CarCatalogServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarCatalogServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CarCatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), CarCatalogServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarCatalogServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CarCatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarCatalogServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CarCatalogServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarCatalogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarService.getAllCarsResponse> CarService.ICarCatalogService.getAllCarsAsync(CarService.getAllCarsRequest request)
        {
            return base.Channel.getAllCarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarService.getAllCarsResponse> getAllCarsAsync()
        {
            CarService.getAllCarsRequest inValue = new CarService.getAllCarsRequest();
            return ((CarService.ICarCatalogService)(this)).getAllCarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarService.reserveResponse> CarService.ICarCatalogService.reserveAsync(CarService.reserveRequest request)
        {
            return base.Channel.reserveAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarService.reserveResponse> reserveAsync(CarService.addReservationDTO reservation)
        {
            CarService.reserveRequest inValue = new CarService.reserveRequest();
            inValue.reservation = reservation;
            return ((CarService.ICarCatalogService)(this)).reserveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarService.getCarResponse> CarService.ICarCatalogService.getCarAsync(CarService.getCarRequest request)
        {
            return base.Channel.getCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarService.getCarResponse> getCarAsync(int id)
        {
            CarService.getCarRequest inValue = new CarService.getCarRequest();
            inValue.id = id;
            return ((CarService.ICarCatalogService)(this)).getCarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarCatalogServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarCatalogServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://desktop-se690ha:8181/GlassFishServer-1.0-SNAPSHOT/CarCatalogServiceServic" +
                        "e");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CarCatalogServiceClient.GetBindingForEndpoint(EndpointConfiguration.CarCatalogServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CarCatalogServiceClient.GetEndpointAddress(EndpointConfiguration.CarCatalogServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            CarCatalogServicePort,
        }
    }
}
